version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: taskflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: taskflow-pro
    networks:
      - taskflow-network

  backend:
    build: .
    container_name: taskflow-backend
    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/taskflow-pro
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - taskflow-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  taskflow-network:
    driver: bridge
